### ISSUE TITLE
findfiles doesnt seem to work with linux relative paths

### ISSUE THREAD

**Issue by issc29** [microsoft/pipelines-appservice-lib#1]
When trying to use [appservice-actions Webapp deployer](https://github.com/Azure/appservice-actions/blob/master/webapp/action.yml), I tried using the `package` syntax with a relative path (or variable) and glob (example: `./target/*.jar` or `${GITHUB_WORKSPACE/target/*.jar}`) and it was not able to pick up the package that I wanted. 

```yaml
    - uses: azure/appservice-actions/webapp@master
      with: 
        app-name: example
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package:  ./target/example*.jar 
```

When I set it to a direct path with glob it worked.  

```yaml
    - uses: azure/appservice-actions/webapp@master
      with: 
        app-name: example
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
        package:  /home/runner/work/example/example/target/example*.jar 
```

I was able to trace it back to this package and I believe there is something wrong in the utility not respecting linux relative paths or environment variables in the path.
